version: '2.2'

services:
  ui:
    image: dmk0062/covid-ui:2.0
    build: ui/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 80:80

  data-service:
    image: dmk0062/covid-data-service:1.0
    build: data-service/
    depends_on:
      - mongo
    restart: always
    network_mode: host
    hostname: localhost
    ports:
      - 8080:8080

  mongo:
    image: mongo:4.0
    restart: always
#    network_mode : host
    hostname : localhost
    ports:
      - 27017:27017
#   volumes:
#     - ../data/mongo:/data/db


