https:
  port: 443
  tls:
    'covidmapper.in':
        key: './ssl/private.key'
        cert: './ssl/certificate.crt'
# http:
#   port: 443
admin:
  port: 9876
  host: localhost
apiEndpoints:
  ui:
    host: covidmapper.in
    paths: '/*'     
  api:
    host: covidmapper.in
    paths: '/api/*'               
serviceEndpoints:
  ui:
    url: 'http://localhost:80/'
  api:
    url: 'http://localhost:8080/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  ui:
    apiEndpoints:
      - ui
    policies:
      - proxy:
          - action:
              serviceEndpoint: ui 
              changeOrigin: true
  api:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: api 
              changeOrigin: true
